let preguntas = [
  { "letra": "A", "pregunta": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "respuesta": "A", "estado": 0, "tipo": "empieza" },
  { "letra": "B", "pregunta": "", "respuesta": "B", "estado": 0, "tipo": "contiene" },
  { "letra": "C", "pregunta": "", "respuesta": "C", "estado": 0, "tipo": "empieza" },
  { "letra": "D", "pregunta": "", "respuesta": "D", "estado": 0, "tipo": "contiene" },
  { "letra": "E", "pregunta": "", "respuesta": "E", "estado": 0, "tipo": "empieza" },
  { "letra": "F", "pregunta": "", "respuesta": "F", "estado": 0, "tipo": "contiene" },
  { "letra": "G", "pregunta": "", "respuesta": "G", "estado": 0, "tipo": "empieza" },
  { "letra": "H", "pregunta": "", "respuesta": "H", "estado": 0, "tipo": "contiene" },
  { "letra": "I", "pregunta": "", "respuesta": "I", "estado": 0, "tipo": "empieza" },
  { "letra": "J", "pregunta": "", "respuesta": "J", "estado": 0, "tipo": "contiene" },
  { "letra": "K", "pregunta": "", "respuesta": "K", "estado": 0, "tipo": "empieza" },
  { "letra": "L", "pregunta": "", "respuesta": "L", "estado": 0, "tipo": "contiene" },
  { "letra": "M", "pregunta": "", "respuesta": "M", "estado": 0, "tipo": "empieza" },
  { "letra": "N", "pregunta": "", "respuesta": "N", "estado": 0, "tipo": "contiene" },
  { "letra": "O", "pregunta": "", "respuesta": "O", "estado": 0, "tipo": "empieza" },
  { "letra": "P", "pregunta": "", "respuesta": "P", "estado": 0, "tipo": "contiene" },
  { "letra": "Q", "pregunta": "", "respuesta": "Q", "estado": 0, "tipo": "empieza" },
  { "letra": "R", "pregunta": "", "respuesta": "R", "estado": 0, "tipo": "contiene" },
  { "letra": "S", "pregunta": "", "respuesta": "S", "estado": 0, "tipo": "empieza" },
  { "letra": "T", "pregunta": "", "respuesta": "T", "estado": 0, "tipo": "contiene" },
  { "letra": "U", "pregunta": "", "respuesta": "U", "estado": 0, "tipo": "empieza" },
  { "letra": "V", "pregunta": "", "respuesta": "V", "estado": 0, "tipo": "contiene" },
  { "letra": "W", "pregunta": "", "respuesta": "W", "estado": 0, "tipo": "empieza" },
  { "letra": "X", "pregunta": "", "respuesta": "X", "estado": 0, "tipo": "contiene" },
  { "letra": "Y", "pregunta": "", "respuesta": "Y", "estado": 0, "tipo": "empieza" },
  { "letra": "Z", "pregunta": "", "respuesta": "Z", "estado": 0, "tipo": "contiene" }
];